### ISSUE TITLE
Warning message of "count_A1" was not set

### ISSUE THREAD

**Issue by yystat** [AlexTISYoung/SNIPar#1]
Hello,

Thanks for sharing this package. I'm trying to use it, and when I run either the example codes (https://sibreg.readthedocs.io/en/master/tutorial.html) or run `impute_runner.py` using my own data, I encountered the following warning. I guess this may not affect the result, but I would like to double check with you. 

Thank you very much!

Here is the warning message:

```
/.local/lib/python3.8/site-packages/pysnptools-0.4.11-py3.8-linux-x86_64.egg/pysnptools/snpreader/bed.py:45: FutureWarning: 'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'
  warnings.warn("'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'", FutureWarning)
```

PS: there's a typo in your installation instruction on the main Github page 'python setupy.py install' should be `python setup.py install`

Josh

**Comment by AlexTISYoung** [comment]
Hi Josh,

Thanks for your email and feedback. The warning message is not important --
it is a warning from Pysnptools which is used to read .bed files, but it
doesn't affect the outcome.

Please let me know if you have any other feedback.

Alex.

**Comment by yystat** [comment]
Ok, thanks!
