### ISSUE TITLE
Imputing missing parental genotype 

### ISSUE THREAD

**Issue by jtahir** [AlexTISYoung/SNIPar#22]
Hi there
I have a question. I have genetic data of female parent, F1s, but missing the male parent. How can I proceed to impute the missing parent data? Do i need to calculate IBDs first.
My data is in the following format;

CHROM	 POS	     Parent 1	Parent2	F1_1	  F1_2 ........F1_199
LG1	       68111 	         A/A		                A/T	  A/C .........  A/A
..
LG29     17,858,85           A/T                           A/A    A/T .........  A/A

There are likely abxaa makers, or vice versa, but its also likely we have abxab calls
thanks

**Comment by AlexTISYoung** [comment]
You don't need to infer IBD if you only have parent offspring data. I
recommend reading the guide and running through the tutorial:
https://snipar.readthedocs.io/en/latest/guide.html
https://snipar.readthedocs.io/en/latest/tutorial.html

**Comment by jtahir** [comment]
Hi 
I am trying to run impute.py scrip on the following subset file but its not working. Could it be I don't have age or sex file for the siblings. 
https://drive.google.com/file/d/143TUSecFigU7KRZmU16Y7rx7tl8bQAlW/view?usp=sharing 
[https://drive.google.com/file/d/143TUSecFigU7KRZmU16Y7rx7tl8bQAlW/view?usp=sharing](url)

**Comment by AlexTISYoung** [comment]
You need to have your genotypes in .bed or .bgen file format.
