### ISSUE TITLE
Error：Less than 50% of SNPs have  genetic positions in genetic map file

### ISSUE THREAD

**Issue by sherryfan030** [AlexTISYoung/SNIPar#24]
Hi there
Thanks for your excellent work on the development of this useful tool! I got an error when used it in my family data as follows:

$ ibd.py --bgen chr1.phased --pedigree pedigree.txt --map geneticmap1000G_chr1b37.txt --out chr1 --threads 12 --ld_out
Number of threads: 12
Reading pedigree from pedigree.txt
Found 38 full sibling pairs
No genotyping error probability provided. Will attempt to estimate from parent-offspring pairs.
86 parent-offspring pairs found in chr1.phased.bgen
Estimated mean genotyping error probability: 1e-06
Reading genotypes from chr1.phased.bgen
Inferring IBD for chromosome 0
reading -- time=0:00:11.95, thread 1 of 12, part 19,323 of 19,323
Calculating allele frequencies
38 sibpairs have genotypes
Before filtering on MAF, missingness, and genotyping error, there were 231869 SNPs
After filtering, there are 191618 SNPs
Reading map from geneticmap1000G_chr1b37.txt
Traceback (most recent call last):
  File "/home/sherry/anaconda3/bin/ibd.py", line 171, in <module>
    main(args)
  File "/home/sherry/anaconda3/bin/ibd.py", line 164, in main
    snipar.ibd.infer_ibd_chr(sibpairs, error_prob, error_probs_i, outprefix,
  File "/home/sherry/anaconda3/lib/python3.9/site-packages/snipar/ibd.py", line 375, in infer_ibd_chr
    gts.map = get_map_positions(mapfile, gts)
  File "/home/sherry/anaconda3/lib/python3.9/site-packages/snipar/map.py", line 65, in get_map_positions
    raise(ValueError('Only '+str(round(100*prop_in_map))+'% of SNPs have genetic positions in '+mapfile+'. Need at least '+str(round(100*min_map_prop))+'%'))
ValueError: Only 33% of SNPs have genetic positions in geneticmap1000G_chr1b37.txt. Need at least 50%

The genetic map files are from 1000G.V3 reference panel provided by impute2 website(https://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3.html) and I used them to phase and impute my genotype data before mendelian imputation. I don't know why to produce this error because I think that most of the genetic variants I input also exist in 1000G panel. Do you have any suggestions?

Best regards!

**Comment by sherryfan030** [comment]
PS: I have filtered SNPs with low quality as described in the tutorial.

**Comment by sherryfan030** [comment]
We have finally resolved it and hereby close the issues

**Comment by AlexTISYoung** [comment]
Hi sorry for the slow reply.

Did you discover any bug in the software?

Thanks,

Alex
