### ISSUE TITLE
IndexError in fGWAS.py when the number of SNPs in observed bim files not equal to the number in imputed data

### ISSUE THREAD

**Issue by yystat** [AlexTISYoung/SNIPar#3]
Hello,

So the error message is:
```
Traceback (most recent call last):
  File "/SNIPar/fGWAS.py", line 213, in <module>
    imp_gts = imp_gts[:,filter_pass]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 131137 but corresponding boolean dimension is 131138
```
This is because the number of SNPs in the "observed" bim file does not equal to that in the imputed data. I think you could re-create this error if you intentionally remove 1 or more SNPs from the observed bim file. `fGWAS.py` does not consider this situation.

Curiously, the reason for unequal number of SNPs is somehow due to the `np.loadtxt()` function on line 149. In my bim file, one SNP has a very very long ID, and somehow `loadtxt()` function only read part of this string while imputation correctly keeps the ID, and as a result, this SNP's IDs are not matched.

Thank you!
Josh

**Comment by AlexTISYoung** [comment]
Hi Josh, do you still have a problem with this?

**Comment by yystat** [comment]
Yes, even after removing the SNPs with very long IDs, I still get this error. 

I'm not familiar with python, but I think the problem could be on line 193 `obs_sid_index = np.zeros((imp_sid.shape[0]),dtype=int)` and the following the `for` loop. Seems the goal of the loop is to keep only the intersecting SNPs, however, line 193 initiate the array with all `0's`, therefore, even if a SNP is not in `obs_sid_dict`, the index will still be 0, as a result, `sid` will have the same length with `imp_sid` (therefore, line 198 should be `sid = imp_sid[obs_sid_index]`?) and contain duplicates of the 1st SNP.

After comparing the contents of `obs_sid` and `imp_sid`, I found that `imp_sid` correctly keeps all the SNP IDs in the bim file, however, some **IDs are not correctly read** in `obs_sid`. These SNP IDs have one common feature: their IDs have the format of `chr:bp:A1_A2` such as "17:44293205_A_G", however, in `obs_sid` it becomes `17:44293205_A_`. (Not all IDs with this format have this problem, e.g., "17:834_G_A" works just fine.) As a result, these SNPs cannot satisfy the `if imp_sid[i] in obs_sid_dict` condition. Together with the above reason, it leads to the "index error". Therefore, the reason for this "index error" is that the code sometimes does not read the `.bim` file correctly and the codes could not exclude those mismatched SNPs.

Another potential issue is that python dictionary does not support duplicate keys, however, it's not uncommon to have duplicate SNP IDs in genotype data. I think it might be safer to first check and remove the SNPs with duplicate IDs.

Thanks!

**Comment by AlexTISYoung** [comment]
Hi Josh, thanks for the detailed info. Could you possibly share your .bim file with me so that I can investigate? My email is alextisyoung@gmail.com.

**Comment by yystat** [comment]
Jul. 30, 2020's update fixed the issue. 
Thanks!
