### ISSUE TITLE
Effective sample size not found in GWAS output

### ISSUE THREAD

**Issue by yystat** [AlexTISYoung/SNIPar#5]
Dear Prof.,

In your paper you mentioned that SNIPar could report an effective sample size for each SNP. However, I do not seem to find this quantity in `fGWAS.py` output. Or could I compute it myself? Thanks!

Josh

**Comment by yystat** [comment]
one more quick question: it seems in `fGWAS.py`, the phenotype `y` is only centered to 0 but not scaled to have variance of 1, is this correct?

Thank you.

**Comment by AlexTISYoung** [comment]
Hi Josh,

It is not output by the software but I will add it if you think that would
be useful.  There is a formula for computing it in the methods section of
the paper though.

You are correct that the phenotype is centred but not scaled.

Thanks,

Alex.

**Comment by yystat** [comment]
That will be great if you could add it since my downstream analysis requires sample sizes.
Thank you so much!

Josh

**Comment by yystat** [comment]
One more question, one line 275 of `fGWAS.py`:
```
alpha_ses = np.sqrt(np.diagonal(alpha_cov,axis1=1,axis2=2))
```
I'm wondering whether there should be a `sqrt(MSE)` term?

Thanks!

**Comment by AlexTISYoung** [comment]
Hi Josh,

I'm not sure what you mean by this?

Thanks,

Alex.

**Comment by yystat** [comment]
I'm assuming this line computes the standard error of effect size estimates?
Since Var(beta_hat) = (X'X)^-1Var(Y) = (X'X)^-1sigma^2, where sigma^2 can be estimated by the MSE. It seems to me that `alpha_ses` only computes the square root of the inverse of X'X.

**Comment by AlexTISYoung** [comment]
You are correct when you are doing standard OLS. However, the script first
estimates the phenotypic covariance matrix by maximum likelihood inference
of the variance explained by differences in family mean (random family
level effect) and the residual variance. It then does a transformation
based on a cholesky decomposition of this covariance matrix, which
effectively rescales everything to be equivalent to doing an OLS regression
with an identity covariance matrix, so the inverse of X'X in this case does
give the correct covariance matrix/standard errors.

Thanks,

Alex.

**Comment by yystat** [comment]
I see. 
Thanks for the clarification!

Josh
