### ISSUE TITLE
negative imputed genotype

### ISSUE THREAD

**Issue by yystat** [AlexTISYoung/SNIPar#8]
Hello, 

Curiously I just found that a few SNP's imputed genotype is negative! Most of them are -1, some -0.5. Is this possible? I'm using parent-offsprings data. (Full sibling data seems to be fine.) Any suggestions how should I treat them? Recode them to NA?
Thanks!

Josh

**Comment by MoeenNehzati** [comment]
Hi,
My guess is they are negative since the IBD inference for those SNPs is incorrectly state 0. I think replacing them with some form of NaN value is the best course of action. I'll fix the package to convert these negative values to NaN before returning them.
Best,
Moeen

**Comment by yystat** [comment]
Got it, thanks!
